### ISSUE TITLE
[INFO] Can this be used with a Docker Swarm service to forward writes to one instance only?

### ISSUE THREAD

**Issue by robertofabrizi** [severalnines/proxysql-docker#1]
Hello everyone,
I've deployed a Galera cluster as a Docker Swarm service:

`qzdxf32y0me8        conductor_mysql-service              replicated          3/3                 percona/percona-xtradb-cluster:5.7.21                     *:3306->3306/tcp`

The problem is that the application that I'm trying to use (Netflix's Conductor) receives this exception, most likely due to the fact that the transaction is split round-robin against the three instances of the Galera MySql container:

`conductor_conductor-server.1.an3u94easnxb@maas_2    | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: WSREP detected deadlock/conflict and aborted the transaction. Try restarting the transaction`

Is it possible to use the proxysql-docker to enable a "sticky session" of sorts?
Thank you,
Roberto

**Comment by ashraf-s9s** [comment]
Hello @robertofabrizi 

It is possible. You can use the Galera example config as shown in the readme of this repository. It is configured with 2 hostgroups. Hostgroup 10 is for single writer and hostgroup 20 is for multi-writer. Create a query rule specifically for your use case in the config file, for example:

```
                rule_id=210
                active=1
                match_pattern=".*"
                destination_hostgroup=10
                sticky_conn=1
                username=conductor
                database=conductor
                apply=1
        },
```
And mount it into the running container. The above will instruct ProxySQL to send all queries sent by MySQL user "conductor" and database "conductor" to hostgroup 10 (single-writer).

**Comment by robertofabrizi** [comment]
Dear @ashraf-s9s , I'm still not sure how to do that though. I'm running a Galera cluster with Docker Swarm, this means that I can't really write down something like this:
```
mysql_servers =
(
        { address="db1.cluster.local" , port=3306 , hostgroup=10, max_connections=100 },
        { address="db2.cluster.local" , port=3306 , hostgroup=10, max_connections=100 },
        { address="db3.cluster.local" , port=3306 , hostgroup=10, max_connections=100 },
        { address="db1.cluster.local" , port=3306 , hostgroup=20, max_connections=100 },
        { address="db2.cluster.local" , port=3306 , hostgroup=20, max_connections=100 },
        { address="db3.cluster.local" , port=3306 , hostgroup=20, max_connections=100 }
)
```

because I don't have anything "static" like db1.cluster.local, all I have is the Docker Swarm VIP / service_name called conductor_mysql-service, and behind that VIP there are the n Galera containers.

Basically, my applications reach the database at conductor_mysql-service:3306, regardless of how many running instances of Galera are behind that VIP at any one point in time, therefore I don't understand how I can create a static list like the one above, I have only one address, one port and consequently one hostgroup...

**Comment by ashraf-s9s** [comment]
Hi @robertofabrizi 

Frankly speaking, the deployment approach that you are using is not compatible with this Docker image. Firstly, you need a resolvable name and it must be static. There is a trick to create each DB container as a Swarm Service, with replicas=1. You will then have three different services, each Swarm service represents a Galera node. You will get a static name and/or VIP (similar to conductor_mysql-service:3306) and then you can map them into ProxySQL image as shown in the previous reply.

You can then manage ProxySQL configuration file by using Docker Swarm Configs for the ProxySQL Swarm service. Details at https://docs.docker.com/engine/swarm/configs/

**Comment by robertofabrizi** [comment]
Dear @ashraf-s9s , you've been of great help understanding how I can reshape my deployment to achieve HA while not breaking everything. I guess that I have one final question if I may abuse your patience. What breaks Netflix's Conductor in the Galera scenario is that they use a transaction to select a table used as a queue, and that causes deadlock issues with the master/master Galera cluster. Is it possible to configure ProxySQL to forward "transactions" from start to end only towards a specific cluster node? I've only seen filters using SELECT or DELETE so I'm not entirely sure how and if that'd be doable. Again thank you so much for your help, best regards,
Roberto

**Comment by robertofabrizi** [comment]
Thanks for the help @ashraf-s9s , I've redeployed the db the way that you suggested and now it seems to be working!
