### ISSUE TITLE
Make the entrypoint.sh script executable in version 2.3

### ISSUE THREAD

**Issue by jagretti** [severalnines/proxysql-docker#10]
As the title says, it seems like in the latest version `2.3` the `entrypoint.sh` script is not executable, so when you want to use it throws this error `exec: permission denied`.

I think that doing this file executable should fix this.

Thank you for doing this, the image works amazing in kubernetes using this tutorial https://severalnines.com/database-blog/proxysql-native-clustering-kubernetes.

**Comment by l00v3** [comment]
Why is this not solved after half a year? I still get the above error.
