### ISSUE TITLE
Proxysql not picking up mysql_variables

### ISSUE THREAD

**Issue by mariojacobo** [severalnines/proxysql-docker#6]
I've deployed ProxySQL on top of Kubernetes (as a service), and for some odd reason, it's not picking up the mysql_variables declared in the configmap. 

config-map
```
mysql_variables=
{
        threads=4
        max_connections=2048
        mysql-max_allowed_packet=1073741824
        mysql-query_retries_on_failure=5
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:6033;/tmp/proxysql.sock"
        default_schema="information_schema"
        stacksize=1048576
        server_version="5.1.30"
        connect_timeout_server=10000
        monitor_history=60000
        monitor_connect_interval=200000
        monitor_ping_interval=200000
        ping_interval_server_msec=10000
        ping_timeout_server=200
        commands_stats=true
        sessions_sort=true
        monitor_username="proxysql"
        monitor_password="myawesomepassword001"
}
```
```
kubectl describe cm proxysql-configmap1 | grep mysql_variables -A 4
mysql_variables=
{
        threads=4
        max_connections=2048
        mysql-max_allowed_packet=1073741824
```

Connecting to the POD with admin credentials, the correct proxysql.cnf is present
```
root@proxysql2-57cc6d5dcb-qhwdz:/# cat /etc/proxysql.cnf |grep mysql_variables -A 4
mysql_variables=
{
        threads=4
        max_connections=2048
        mysql-max_allowed_packet=1073741824
```

Connecting to the ProxySQL DB from inside the POD or to the service directly, aside from max_connections and threads, the rest are ignored and are default still. The same happens for any other variables I declare.
```
MySQL [(none)]> show variables like '%allowed%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| mysql-max_allowed_packet | 4194304 |
```

I've deleted the deployment, configmaps, and then redeployed, but still I'm facing the same issues. Can these be changed, or better yet should they be changed ? I wanted to set the max allowed packet value equal to what I have on the backend nodes in Percona XtraDB cluster.

**Comment by ashraf-s9s** [comment]
Hi @mariojacobo 

The variable names in the configuration file are a bit different than what are loaded inside ProxySQL. Inside proxysql.cnf, all variables under mysql_variables array will be automatically prepended with ``mysql-`` when being parsed and loaded into ProxySQL. Hence, you don't need to specify the ``mysql-`` prefix in the configuration line.

The correct variable name in the configuration file should be:
```
mysql_variables = 
{
    ....
    max_allowed_packet=1073741824
    ...
}
```

The same format applies to admin variable group as well. Instead of ``admin-admin_credentials``, you have to write it down in the config file as:
```
admin_variables = 
{
    admin_credentials="admin:mys3cr3t"
    ...
}
```

**Comment by mariojacobo** [comment]
that makes sense, didn't pick up on that. much appreciated
